services:

  node-exporter:

    image: prom/node-exporter

    container_name: node-exporter

    ports:
      - "9100:9100"

    restart: always

    networks:
      - backend

  prometheus:

    image: prom/prometheus

    container_name: prometheus

    volumes:

      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:

      - "9093:9090"

    depends_on:

      - node-exporter
    
    networks:
      - backend

  grafana:

    image: grafana/grafana

    container_name: grafana

    ports:

      - "3000:3000"

    depends_on:

      - prometheus

    networks:
      - backend

  loki:
    image: grafana/loki:latest
    container_name: loki

    ports:
      - "3100:3100"

    volumes:
      - ./loki/loki-config.yml:/etc/loki/config.yml

    command: -config.file=/etc/loki/config.yml

    networks:
      - backend

  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy

    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345

    depends_on:
      - loki

    networks:
      - backend

networks:
  backend:
    external: true
    name: docker_backend
